CREATE TABLE Instructor
(
	Email VARCHAR(255),
	FirstName VARCHAR(255),
	LastName VARCHAR(255),
	PRIMARY KEY (Email)
) ENGINE=InnoDB;

CREATE TABLE Course
(
	ID INT AUTO_INCREMENT NOT NULL,
	Dept VARCHAR(4) NOT NULL,
	CourseNumber INT NOT NULL,
	Title VARCHAR(255) NOT NULL,
	CreditHours INT NOT NULL,
	Description TEXT NOT NULL DEFAULT '',
	Structure TEXT NOT NULL DEFAULT '',
	PRIMARY KEY(ID),
	UNIQUE (Dept, CourseNumber),
	UNIQUE (Dept, Title)
) ENGINE=InnoDB;

CREATE TABLE CourseInstance
(
	ID INT AUTO_INCREMENT NOT NULL,
	CourseID INT NOT NULL,
	Instructor VARCHAR(255) NOT NULL,
	TermID INT(6) NOT NULL,
	State ENUM ('Sent', 'Approved', 'Ready', 'Finalized') NOT NULL DEFAULT 'Sent',
	CommentPrep TEXT NOT NULL DEFAULT '',
	CommentPrepActions TEXT NOT NULL DEFAULT '',
	CommentChanges TEXT NOT NULL DEFAULT '',
	CommentCLO TEXT NOT NULL DEFAULT '',
	CommentRecs TEXT NOT NULL DEFAULT '',
	PRIMARY KEY (ID),
	UNIQUE (CourseID, Instructor, TermID),
	FOREIGN KEY (CourseID) REFERENCES Course (ID) ON UPDATE CASCADE,
	FOREIGN KEY (Instructor) REFERENCES Instructor (Email) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CLO
(
	ID INT AUTO_INCREMENT NOT NULL,
	CourseID INT,
	CLONumber INT,
	Description TEXT,
	PRIMARY KEY (ID),
	FOREIGN KEY (CourseID) REFERENCES Course (ID) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CLOOutcomes
(
	CLOID INT NOT NULL,
	ABETOutcome CHAR(1) NOT NULL,
	PRIMARY KEY (CLOID, ABETOutcome),
	FOREIGN KEY (CLOID) REFERENCES CLO (ID) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MasterCLO
(
	CLOID INT NOT NULL,
	CourseID INT NOT NULL,
	PRIMARY KEY (CLOID, CourseID),
	FOREIGN KEY (CLOID) REFERENCES CLO (ID) ON UPDATE CASCADE,
	FOREIGN KEY (CourseID) REFERENCES Course (ID) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CourseInstanceCLO
(
	CLOID INT NOT NULL,
	CourseInstanceID INT NOT NULL,
	Assessed VARCHAR(255),
	MeanScore INT,
	MedianScore INT,
	HighScore INT,
	SatisfactoryScore INT,
	PRIMARY KEY (CLOID, CourseInstanceID),
	FOREIGN KEY (CLOID) REFERENCES CLO (ID) ON UPDATE CASCADE,
	FOREIGN KEY (CourseInstanceID) REFERENCES CourseInstance (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Prerequisites
(
	CourseID INT NOT NULL,
	PrerequisiteID INT NOT NULL,
	IsCorequisite BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY (CourseID, PrerequisiteID),
	FOREIGN KEY (CourseID) REFERENCES Course (ID) ON UPDATE CASCADE,
	FOREIGN KEY (PrerequisiteID) REFERENCES Course (ID) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TermsOffered
(
	CourseID INT NOT NULL,
	Summer BOOL NOT NULL DEFAULT 0,
	Fall BOOL NOT NULL DEFAULT 0,
	Winter BOOL NOT NULL DEFAULT 0,
	Spring BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY (CourseID),
	FOREIGN KEY (CourseID) REFERENCES Course (ID) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TermState
(
	TermID INT(6) NOT NULL,
	State ENUM ('Sent', 'Approved', 'Ready', 'Finalized') NOT NULL DEFAULT 'Sent',
	PRIMARY KEY (Term)
) ENGINE=InnoDB;
